#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SunyuCRM_V3")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertMarketing_MsgPool(Marketing_MsgPool instance);
    partial void UpdateMarketing_MsgPool(Marketing_MsgPool instance);
    partial void DeleteMarketing_MsgPool(Marketing_MsgPool instance);
    partial void InsertMarketing_MsgQueue(Marketing_MsgQueue instance);
    partial void UpdateMarketing_MsgQueue(Marketing_MsgQueue instance);
    partial void DeleteMarketing_MsgQueue(Marketing_MsgQueue instance);
    partial void InsertMarketing_WechatPool(Marketing_WechatPool instance);
    partial void UpdateMarketing_WechatPool(Marketing_WechatPool instance);
    partial void DeleteMarketing_WechatPool(Marketing_WechatPool instance);
    partial void InsertMarketing_WechatQueue(Marketing_WechatQueue instance);
    partial void UpdateMarketing_WechatQueue(Marketing_WechatQueue instance);
    partial void DeleteMarketing_WechatQueue(Marketing_WechatQueue instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::DB_Entity.Properties.Settings.Default.SunyuCRM_V3ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Marketing_MsgPool> Marketing_MsgPool
		{
			get
			{
				return this.GetTable<Marketing_MsgPool>();
			}
		}
		
		public System.Data.Linq.Table<Marketing_MsgQueue> Marketing_MsgQueue
		{
			get
			{
				return this.GetTable<Marketing_MsgQueue>();
			}
		}
		
		public System.Data.Linq.Table<Marketing_WechatPool> Marketing_WechatPool
		{
			get
			{
				return this.GetTable<Marketing_WechatPool>();
			}
		}
		
		public System.Data.Linq.Table<Marketing_WechatQueue> Marketing_WechatQueue
		{
			get
			{
				return this.GetTable<Marketing_WechatQueue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marketing_MsgPool")]
	public partial class Marketing_MsgPool : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _MsgChannel;
		
		private string _Email;
		
		private string _UserCode;
		
		private string _Mobile;
		
		private string _TemplateCode;
		
		private string _MsgTitle;
		
		private string _MsgContent;
		
		private System.Nullable<int> _Priority;
		
		private System.Nullable<int> _Status;
		
		private System.DateTime _ExpectedTime;
		
		private System.Nullable<int> _SendCount;
		
		private string _MsgBatchCode;
		
		private System.Nullable<int> _RefType;
		
		private string _RefCode;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private string _Memo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMsgChannelChanging(System.Nullable<int> value);
    partial void OnMsgChannelChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnTemplateCodeChanging(string value);
    partial void OnTemplateCodeChanged();
    partial void OnMsgTitleChanging(string value);
    partial void OnMsgTitleChanged();
    partial void OnMsgContentChanging(string value);
    partial void OnMsgContentChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnExpectedTimeChanging(System.DateTime value);
    partial void OnExpectedTimeChanged();
    partial void OnSendCountChanging(System.Nullable<int> value);
    partial void OnSendCountChanged();
    partial void OnMsgBatchCodeChanging(string value);
    partial void OnMsgBatchCodeChanged();
    partial void OnRefTypeChanging(System.Nullable<int> value);
    partial void OnRefTypeChanged();
    partial void OnRefCodeChanging(string value);
    partial void OnRefCodeChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    #endregion
		
		public Marketing_MsgPool()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgChannel", DbType="Int")]
		public System.Nullable<int> MsgChannel
		{
			get
			{
				return this._MsgChannel;
			}
			set
			{
				if ((this._MsgChannel != value))
				{
					this.OnMsgChannelChanging(value);
					this.SendPropertyChanging();
					this._MsgChannel = value;
					this.SendPropertyChanged("MsgChannel");
					this.OnMsgChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="NVarChar(100)")]
		public string UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateCode", DbType="NVarChar(50)")]
		public string TemplateCode
		{
			get
			{
				return this._TemplateCode;
			}
			set
			{
				if ((this._TemplateCode != value))
				{
					this.OnTemplateCodeChanging(value);
					this.SendPropertyChanging();
					this._TemplateCode = value;
					this.SendPropertyChanged("TemplateCode");
					this.OnTemplateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgTitle", DbType="NVarChar(50)")]
		public string MsgTitle
		{
			get
			{
				return this._MsgTitle;
			}
			set
			{
				if ((this._MsgTitle != value))
				{
					this.OnMsgTitleChanging(value);
					this.SendPropertyChanging();
					this._MsgTitle = value;
					this.SendPropertyChanged("MsgTitle");
					this.OnMsgTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgContent", DbType="NVarChar(MAX)")]
		public string MsgContent
		{
			get
			{
				return this._MsgContent;
			}
			set
			{
				if ((this._MsgContent != value))
				{
					this.OnMsgContentChanging(value);
					this.SendPropertyChanging();
					this._MsgContent = value;
					this.SendPropertyChanged("MsgContent");
					this.OnMsgContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedTime", DbType="DateTime NOT NULL")]
		public System.DateTime ExpectedTime
		{
			get
			{
				return this._ExpectedTime;
			}
			set
			{
				if ((this._ExpectedTime != value))
				{
					this.OnExpectedTimeChanging(value);
					this.SendPropertyChanging();
					this._ExpectedTime = value;
					this.SendPropertyChanged("ExpectedTime");
					this.OnExpectedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendCount", DbType="Int")]
		public System.Nullable<int> SendCount
		{
			get
			{
				return this._SendCount;
			}
			set
			{
				if ((this._SendCount != value))
				{
					this.OnSendCountChanging(value);
					this.SendPropertyChanging();
					this._SendCount = value;
					this.SendPropertyChanged("SendCount");
					this.OnSendCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgBatchCode", DbType="NVarChar(64)")]
		public string MsgBatchCode
		{
			get
			{
				return this._MsgBatchCode;
			}
			set
			{
				if ((this._MsgBatchCode != value))
				{
					this.OnMsgBatchCodeChanging(value);
					this.SendPropertyChanging();
					this._MsgBatchCode = value;
					this.SendPropertyChanged("MsgBatchCode");
					this.OnMsgBatchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefType", DbType="Int")]
		public System.Nullable<int> RefType
		{
			get
			{
				return this._RefType;
			}
			set
			{
				if ((this._RefType != value))
				{
					this.OnRefTypeChanging(value);
					this.SendPropertyChanging();
					this._RefType = value;
					this.SendPropertyChanged("RefType");
					this.OnRefTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCode", DbType="VarChar(100)")]
		public string RefCode
		{
			get
			{
				return this._RefCode;
			}
			set
			{
				if ((this._RefCode != value))
				{
					this.OnRefCodeChanging(value);
					this.SendPropertyChanging();
					this._RefCode = value;
					this.SendPropertyChanged("RefCode");
					this.OnRefCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(1000)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marketing_MsgQueue")]
	public partial class Marketing_MsgQueue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private System.Nullable<int> _MsgChannel;
		
		private string _Email;
		
		private string _UserCode;
		
		private string _Mobile;
		
		private string _TemplateCode;
		
		private string _MsgTitle;
		
		private string _MsgContent;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<System.DateTime> _LastSendTime;
		
		private System.Nullable<int> _Priority;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<System.DateTime> _ExpectedTime;
		
		private System.Nullable<int> _SendCount;
		
		private string _MsgBatchCode;
		
		private System.Nullable<int> _RefType;
		
		private string _RefCode;
		
		private System.Nullable<int> _MsgQId;
		
		private System.Nullable<System.DateTime> _RecvTime;
		
		private string _Memo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnMsgChannelChanging(System.Nullable<int> value);
    partial void OnMsgChannelChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnTemplateCodeChanging(string value);
    partial void OnTemplateCodeChanged();
    partial void OnMsgTitleChanging(string value);
    partial void OnMsgTitleChanged();
    partial void OnMsgContentChanging(string value);
    partial void OnMsgContentChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnLastSendTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastSendTimeChanged();
    partial void OnPriorityChanging(System.Nullable<int> value);
    partial void OnPriorityChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnExpectedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnExpectedTimeChanged();
    partial void OnSendCountChanging(System.Nullable<int> value);
    partial void OnSendCountChanged();
    partial void OnMsgBatchCodeChanging(string value);
    partial void OnMsgBatchCodeChanged();
    partial void OnRefTypeChanging(System.Nullable<int> value);
    partial void OnRefTypeChanged();
    partial void OnRefCodeChanging(string value);
    partial void OnRefCodeChanged();
    partial void OnMsgQIdChanging(System.Nullable<int> value);
    partial void OnMsgQIdChanged();
    partial void OnRecvTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnRecvTimeChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    #endregion
		
		public Marketing_MsgQueue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="VarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgChannel", DbType="Int")]
		public System.Nullable<int> MsgChannel
		{
			get
			{
				return this._MsgChannel;
			}
			set
			{
				if ((this._MsgChannel != value))
				{
					this.OnMsgChannelChanging(value);
					this.SendPropertyChanging();
					this._MsgChannel = value;
					this.SendPropertyChanged("MsgChannel");
					this.OnMsgChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="NVarChar(50)")]
		public string UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TemplateCode", DbType="NVarChar(50)")]
		public string TemplateCode
		{
			get
			{
				return this._TemplateCode;
			}
			set
			{
				if ((this._TemplateCode != value))
				{
					this.OnTemplateCodeChanging(value);
					this.SendPropertyChanging();
					this._TemplateCode = value;
					this.SendPropertyChanged("TemplateCode");
					this.OnTemplateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgTitle", DbType="NVarChar(50)")]
		public string MsgTitle
		{
			get
			{
				return this._MsgTitle;
			}
			set
			{
				if ((this._MsgTitle != value))
				{
					this.OnMsgTitleChanging(value);
					this.SendPropertyChanging();
					this._MsgTitle = value;
					this.SendPropertyChanged("MsgTitle");
					this.OnMsgTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgContent", DbType="NVarChar(MAX)")]
		public string MsgContent
		{
			get
			{
				return this._MsgContent;
			}
			set
			{
				if ((this._MsgContent != value))
				{
					this.OnMsgContentChanging(value);
					this.SendPropertyChanging();
					this._MsgContent = value;
					this.SendPropertyChanged("MsgContent");
					this.OnMsgContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSendTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastSendTime
		{
			get
			{
				return this._LastSendTime;
			}
			set
			{
				if ((this._LastSendTime != value))
				{
					this.OnLastSendTimeChanging(value);
					this.SendPropertyChanging();
					this._LastSendTime = value;
					this.SendPropertyChanged("LastSendTime");
					this.OnLastSendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int")]
		public System.Nullable<int> Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpectedTime
		{
			get
			{
				return this._ExpectedTime;
			}
			set
			{
				if ((this._ExpectedTime != value))
				{
					this.OnExpectedTimeChanging(value);
					this.SendPropertyChanging();
					this._ExpectedTime = value;
					this.SendPropertyChanged("ExpectedTime");
					this.OnExpectedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendCount", DbType="Int")]
		public System.Nullable<int> SendCount
		{
			get
			{
				return this._SendCount;
			}
			set
			{
				if ((this._SendCount != value))
				{
					this.OnSendCountChanging(value);
					this.SendPropertyChanging();
					this._SendCount = value;
					this.SendPropertyChanged("SendCount");
					this.OnSendCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgBatchCode", DbType="NVarChar(64)")]
		public string MsgBatchCode
		{
			get
			{
				return this._MsgBatchCode;
			}
			set
			{
				if ((this._MsgBatchCode != value))
				{
					this.OnMsgBatchCodeChanging(value);
					this.SendPropertyChanging();
					this._MsgBatchCode = value;
					this.SendPropertyChanged("MsgBatchCode");
					this.OnMsgBatchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefType", DbType="Int")]
		public System.Nullable<int> RefType
		{
			get
			{
				return this._RefType;
			}
			set
			{
				if ((this._RefType != value))
				{
					this.OnRefTypeChanging(value);
					this.SendPropertyChanging();
					this._RefType = value;
					this.SendPropertyChanged("RefType");
					this.OnRefTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCode", DbType="VarChar(100)")]
		public string RefCode
		{
			get
			{
				return this._RefCode;
			}
			set
			{
				if ((this._RefCode != value))
				{
					this.OnRefCodeChanging(value);
					this.SendPropertyChanging();
					this._RefCode = value;
					this.SendPropertyChanged("RefCode");
					this.OnRefCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgQId", DbType="Int")]
		public System.Nullable<int> MsgQId
		{
			get
			{
				return this._MsgQId;
			}
			set
			{
				if ((this._MsgQId != value))
				{
					this.OnMsgQIdChanging(value);
					this.SendPropertyChanging();
					this._MsgQId = value;
					this.SendPropertyChanged("MsgQId");
					this.OnMsgQIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecvTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> RecvTime
		{
			get
			{
				return this._RecvTime;
			}
			set
			{
				if ((this._RecvTime != value))
				{
					this.OnRecvTimeChanging(value);
					this.SendPropertyChanging();
					this._RecvTime = value;
					this.SendPropertyChanged("RecvTime");
					this.OnRecvTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(500)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marketing_WechatPool")]
	public partial class Marketing_WechatPool : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CustCode;
		
		private System.Nullable<int> _WechatChannel;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<System.DateTime> _PushTime;
		
		private string _Memo;
		
		private string _RefCode;
		
		private System.Nullable<int> _RefType;
		
		private string _ParamSet;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCustCodeChanging(string value);
    partial void OnCustCodeChanged();
    partial void OnWechatChannelChanging(System.Nullable<int> value);
    partial void OnWechatChannelChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnPushTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPushTimeChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnRefCodeChanging(string value);
    partial void OnRefCodeChanged();
    partial void OnRefTypeChanging(System.Nullable<int> value);
    partial void OnRefTypeChanged();
    partial void OnParamSetChanging(string value);
    partial void OnParamSetChanged();
    #endregion
		
		public Marketing_WechatPool()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustCode", DbType="VarChar(64)")]
		public string CustCode
		{
			get
			{
				return this._CustCode;
			}
			set
			{
				if ((this._CustCode != value))
				{
					this.OnCustCodeChanging(value);
					this.SendPropertyChanging();
					this._CustCode = value;
					this.SendPropertyChanged("CustCode");
					this.OnCustCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WechatChannel", DbType="Int")]
		public System.Nullable<int> WechatChannel
		{
			get
			{
				return this._WechatChannel;
			}
			set
			{
				if ((this._WechatChannel != value))
				{
					this.OnWechatChannelChanging(value);
					this.SendPropertyChanging();
					this._WechatChannel = value;
					this.SendPropertyChanged("WechatChannel");
					this.OnWechatChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PushTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PushTime
		{
			get
			{
				return this._PushTime;
			}
			set
			{
				if ((this._PushTime != value))
				{
					this.OnPushTimeChanging(value);
					this.SendPropertyChanging();
					this._PushTime = value;
					this.SendPropertyChanged("PushTime");
					this.OnPushTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(MAX)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCode", DbType="NVarChar(50)")]
		public string RefCode
		{
			get
			{
				return this._RefCode;
			}
			set
			{
				if ((this._RefCode != value))
				{
					this.OnRefCodeChanging(value);
					this.SendPropertyChanging();
					this._RefCode = value;
					this.SendPropertyChanged("RefCode");
					this.OnRefCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefType", DbType="Int")]
		public System.Nullable<int> RefType
		{
			get
			{
				return this._RefType;
			}
			set
			{
				if ((this._RefType != value))
				{
					this.OnRefTypeChanging(value);
					this.SendPropertyChanging();
					this._RefType = value;
					this.SendPropertyChanged("RefType");
					this.OnRefTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParamSet", DbType="NVarChar(MAX)")]
		public string ParamSet
		{
			get
			{
				return this._ParamSet;
			}
			set
			{
				if ((this._ParamSet != value))
				{
					this.OnParamSetChanging(value);
					this.SendPropertyChanging();
					this._ParamSet = value;
					this.SendPropertyChanged("ParamSet");
					this.OnParamSetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marketing_WechatQueue")]
	public partial class Marketing_WechatQueue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CustCode;
		
		private System.Nullable<int> _WechatChannel;
		
		private System.Nullable<System.DateTime> _CreateTime;
		
		private System.Nullable<System.DateTime> _LastSendTime;
		
		private System.Nullable<int> _Status;
		
		private string _Memo;
		
		private string _RefCode;
		
		private System.Nullable<int> _RefType;
		
		private string _ParamSet;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCustCodeChanging(string value);
    partial void OnCustCodeChanged();
    partial void OnWechatChannelChanging(System.Nullable<int> value);
    partial void OnWechatChannelChanged();
    partial void OnCreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateTimeChanged();
    partial void OnLastSendTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastSendTimeChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    partial void OnRefCodeChanging(string value);
    partial void OnRefCodeChanged();
    partial void OnRefTypeChanging(System.Nullable<int> value);
    partial void OnRefTypeChanged();
    partial void OnParamSetChanging(string value);
    partial void OnParamSetChanged();
    #endregion
		
		public Marketing_WechatQueue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustCode", DbType="VarChar(64)")]
		public string CustCode
		{
			get
			{
				return this._CustCode;
			}
			set
			{
				if ((this._CustCode != value))
				{
					this.OnCustCodeChanging(value);
					this.SendPropertyChanging();
					this._CustCode = value;
					this.SendPropertyChanged("CustCode");
					this.OnCustCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WechatChannel", DbType="Int")]
		public System.Nullable<int> WechatChannel
		{
			get
			{
				return this._WechatChannel;
			}
			set
			{
				if ((this._WechatChannel != value))
				{
					this.OnWechatChannelChanging(value);
					this.SendPropertyChanging();
					this._WechatChannel = value;
					this.SendPropertyChanged("WechatChannel");
					this.OnWechatChannelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSendTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastSendTime
		{
			get
			{
				return this._LastSendTime;
			}
			set
			{
				if ((this._LastSendTime != value))
				{
					this.OnLastSendTimeChanging(value);
					this.SendPropertyChanging();
					this._LastSendTime = value;
					this.SendPropertyChanged("LastSendTime");
					this.OnLastSendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NVarChar(MAX)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefCode", DbType="NVarChar(50)")]
		public string RefCode
		{
			get
			{
				return this._RefCode;
			}
			set
			{
				if ((this._RefCode != value))
				{
					this.OnRefCodeChanging(value);
					this.SendPropertyChanging();
					this._RefCode = value;
					this.SendPropertyChanged("RefCode");
					this.OnRefCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefType", DbType="Int")]
		public System.Nullable<int> RefType
		{
			get
			{
				return this._RefType;
			}
			set
			{
				if ((this._RefType != value))
				{
					this.OnRefTypeChanging(value);
					this.SendPropertyChanging();
					this._RefType = value;
					this.SendPropertyChanged("RefType");
					this.OnRefTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParamSet", DbType="NVarChar(MAX)")]
		public string ParamSet
		{
			get
			{
				return this._ParamSet;
			}
			set
			{
				if ((this._ParamSet != value))
				{
					this.OnParamSetChanging(value);
					this.SendPropertyChanging();
					this._ParamSet = value;
					this.SendPropertyChanged("ParamSet");
					this.OnParamSetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
